def utils
def rebaseNeeded       = "-1"
int comment_id         = 0
def allRecipientEmails = ""
def pr_labels          = [ "ManifestUpdateReq ", "BUILD_FAILED", "BUILD_PASSED", "CHECKPATCH_FAILED" ]
def job_config = [
    github_creds_id : "27c5d944-f190-4ab7-8c37-23cc43c7ce11"
]
def updateManifestPRnumber = null
def commentMsg = "✏️ PLEASE UPDATE THIS PR SHA/PULL-NUMBER IN MANIFEST FILE OF ALIF_SDK ✏️"

pipeline {
    agent any

    environment {
        GITHUB_USER_OR_ORG_NAME = sh(script: 'echo ${CHANGE_URL:-alifsemi}    | sed -E "s#https://github.com/([^/]+)/([^/]+)/.*#\\1#"', returnStdout: true).trim()
        GITHUB_REPO_NAME        = sh(script: 'echo ${CHANGE_URL:-zephyr_alif} | sed -E "s#https://github.com/([^/]+)/([^/]+)/.*#\\2#"', returnStdout: true).trim()
        CHANGE_TARGET           = sh(script: 'echo ${CHANGE_TARGET:-main}', returnStdout: true).trim()
        GITHUB_TOKEN            = credentials('27c5d944-f190-4ab7-8c37-23cc43c7ce11')
        PATH                    = "${env.PATH}:$HOME/.local/bin"
    }

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    job_config.owner  = "${GITHUB_USER_OR_ORG_NAME}"
                    job_config.user   = "${GITHUB_TOKEN_USR}"
                    job_config.repo   = "${GITHUB_REPO_NAME}"
                    job_config.branch = "${CHANGE_TARGET}"
                    job_config.token  = GITHUB_TOKEN_PSW
                    job_config.pr_repo        = "${GITHUB_REPO_NAME}"
                    job_config.prNumber       = "${CHANGE_ID}"
                    job_config.manifest_repo  = "sdk-alif"

                    sh '''#!/bin/bash -xe
                    if ! command -v gitlint >/dev/null 2>&1; then
                        echo "gitlint not found. Installing gitlint..."
                        python3 -m pip install --user -q gitlint
                    fi
                    if ! command -v jq >/dev/null 2>&1; then
                        echo "jq not found. Installing..."

                        mkdir -p "$HOME/.local/bin" && wget --tries=5 --timeout=30 --waitretry=5 \
                            --retry-connrefused --https-only -q -O "$HOME/.local/bin/jq" \
                            "https://github.com/jqlang/jq/releases/latest/download/jq-linux-amd64" && \
                        chmod 755 "$HOME/.local/bin/jq"
                    fi
                    git config --list
                    [ -n "$(git config --global --get user.name)" ]  || git config --global user.name "Alif-CI"
                    [ -n "$(git config --global --get user.email)" ] || git config --global user.email "alif-ci@alifsemi.com"
                    '''
                }
            }
        }

        stage('Display Environment Variables') {
            steps {
                script {
                    sh """#!/bin/bash -xe
                        printenv
                        echo -e "🛠️ $PATH"
                        echo -e "✔️ Displayed all environment setting."
                    """
                }
            }
        }

        stage('checkout') {
            steps {
                cleanWs()
                echo "⏳ Checking out '${GITHUB_REPO_NAME}' repo..."

                dir("${GITHUB_REPO_NAME}") {
                    checkout scm
                }
                script {
                    utils = load "${GITHUB_REPO_NAME}/automation/utils/Utils.groovy"
                    utils.init(job_config)
                }

                script {
                    if (utils && utils.github) {
                        withCredentials([usernamePassword(credentialsId: job_config.github_creds_id,
                            usernameVariable: 'GITHUB_TOKEN_USR', passwordVariable: 'GITHUB_TOKEN')]) {
                                for (String label : pr_labels) {
                                    echo "remove existing build label [$label]"
                                    job_config.label = label
                                    utils.github.removeLabel(job_config)
                                }
                        }
                    }

                    rebaseNeeded = sh(
                        script: '''#!/bin/bash
                            set -xe
                            cd ${GITHUB_REPO_NAME}
                            git fetch origin refs/heads/${CHANGE_TARGET}:refs/remotes/origin/${CHANGE_TARGET}

                            if ! git rebase origin/${CHANGE_TARGET} ; then
                                echo -e "Rebase could not happen successfully"
                                exit 1
                            fi

                            commitCnt=$(git rev-list --count origin/${CHANGE_TARGET}..HEAD)
                            commits=$(git log -n ${commitCnt} --pretty=format:"%H")

                            if [[ "$commitCnt" -lt "1" ]] ; then
                                echo 0
                                exit 0
                            fi

                            firstCommit=$(git log -n 1 --pretty=format:"%H")
                            firstCommit_author_name=$(git show -s --format="%an" "$firstCommit")
                            firstCommit_author_email=$(git show -s --format="%ae" "$firstCommit")
                            firstCommit_body=$(git show -s --format="%b" "$firstCommit" | tail -n +1 | awk '!/^[A-Za-z-]+:/ {print}' | sed '/^$/d')
                            parentCnt=$(git log -n 1 --pretty=format:"%p"  | wc -w)

                            if [[ "$firstCommit_author_name" == "Jenkins" || "$firstCommit_author_email" == "nobody@nowhere" || \
                                  "$firstCommit_body" == "*Merge commit \'$firstCommit\' into HEAD*" || "$parentCnt" -gt "1" || \
                                  "$firstCommit_author_name" == "Alif-CI" || "$firstCommit_author_email" == "alif-ci@alifsemi.com" ]] ; then
                                git reset --soft HEAD~1
                                echo 1
                            else
                                echo 0
                            fi
                            ''',
                        returnStdout: true
                    ).trim()
                     echo "🎯 rebase needed: [${rebaseNeeded}]..."
                }
            }
        }

        stage('Get PR Message/Authors') {
            steps {
                script {
                    allRecipientEmails = sh(
                        script: '''#!/bin/bash
                            set -xe
                            cd ${GITHUB_REPO_NAME}
                            commitCnt=$(git rev-list --count origin/${CHANGE_TARGET}..HEAD)

                            # Get all author emails for this PR
                            culpritEmails=$(git log -n $commitCnt --pretty=format:'%ae' | sort | uniq | paste -sd";" -)

                            # Replace all commas with semicolons
                            defaultEmails=$(echo "$DEFAULT_OWNER_EMAILS" | tr ',' ';')

                            all_emails="$culpritEmails;$defaultEmails;test@st.com"
                            all_unique_emails=$(echo "$all_emails" | tr ';' '\n' | grep -v '^$' | sort -u | paste -sd ";" -)
                            echo "$all_unique_emails" | tr ';' '\n' | grep '@alifsemi.com$' | paste -sd';' -
                        ''',
                        returnStdout: true
                    ).trim()
                    echo "📤 Mail will be sent to: [${allRecipientEmails}]..."
                }
            }
        }

        stage('CheckPatch and Commit Message Validation') {
            steps {
                script {
                    catchError(buildResult: 'FAILURE', stageResult: 'FAILURE') {
                        sh """#!/bin/bash
                        set -xe
                        cd \${GITHUB_REPO_NAME}

                        commitCnt=\$(git rev-list --count origin/${CHANGE_TARGET}..HEAD)
                        totalCommitCnt=\$(git rev-list --count origin/${CHANGE_TARGET})

                        if [[ "\$totalCommitCnt" -lt "\$commitCnt" ]] ; then
                            checkGitLog=\${commitCnt}
                        else
                            checkGitLog=6
                        fi
                        git log -\${checkGitLog}

                        echo -e "🎯 we have \$commitCnt commits in \$CHANGE_TARGET review"
                        if [[ "\${commitCnt}" =~ ^[0-9]+\$ && "\${commitCnt}" -gt "0" ]] ; then
                            git format-patch -\${commitCnt}
                            check_patch_output=\$(./scripts/checkpatch.pl --patch *.patch)
                            echo -e "\$check_patch_output"
                            check_patch_output_summary=\$(echo "\$check_patch_output" | grep ".patch total:")
                            echo -e "\$check_patch_output_summary"

                            check_patch_errors=0
                            check_patch_warnings=0
                            check_patch_lines=0

                            while read -r line; do
                              # Extract numbers using regex or field parsing
                              err=\$(echo "\$line"  | awk '{for(i=1;i<=NF;i++) if(\$i=="total:") print \$(i+1)}')
                              warn=\$(echo "\$line" | awk '{for(i=1;i<=NF;i++) if(\$i=="errors,") print \$(i+1)}')
                              ln=\$(echo "\$line"   | awk '{for(i=1;i<=NF;i++) if(\$i=="warnings,") print \$(i+1)}')

                              if [[ "\$err" =~ ^[0-9]+\$ ]]; then
                                check_patch_errors=\$((check_patch_errors + err))
                              else
                                echo "Skipping non-numeric error: \$err"
                              fi

                              if [[ "\$warn" =~ ^[0-9]+\$ ]]; then
                                check_patch_warnings=\$((check_patch_warnings + warn))
                              else
                                echo "Skipping non-numeric warning: \$warn"
                              fi

                              if [[ "\$ln" =~ ^[0-9]+\$ ]]; then
                                check_patch_lines=\$((check_patch_lines + ln))
                              else
                                echo "Skipping non-numeric lines: \$ln"
                              fi

                            done <<< "\$check_patch_output_summary"

                            echo -e "🎯Check-Patch has=> Errors: \${check_patch_errors} Warnings: \${check_patch_warnings}, Lines: \${check_patch_lines}\n\n"

                            gitlint_log=\$(git log -\${commitCnt} --pretty=%B | gitlint 2>&1)
                            if [ -n "\$gitlint_log" ] ; then
                                gitlint_err=1
                                echo -e "🎯GITLINT log=>\n\$gitlint_log"
                            else
                               gitlint_err=0
                            fi
                        else
                            gitlint_err=0
                            check_patch_errors=0
                        fi
                        echo -e " 🏆Git Rebase Needed  =>  ${rebaseNeeded}"
                        echo -e " 🏆GitLint Result     =>  \${gitlint_err}"
                        echo -e " 🏆Check-Patch Result =>  Error: \$check_patch_errors, Warnings: \$check_patch_warnings"
                        if [[ "\${check_patch_errors}" -gt 0 || "\${gitlint_err}" -ne 0 ]]; then
                            exit 1
                        else
                            exit 0
                        fi
                        """
                    }
                }
            }
        }
    }

    post {
        always{
            script {
                if (utils && utils.github && common_funcs) {
                    withCredentials([usernamePassword(credentialsId: job_config.github_creds_id,
                        usernameVariable: 'GITHUB_TOKEN_USR', passwordVariable: 'GITHUB_TOKEN')]) {

                            String searchText =
                                "https://github.com/${job_config.owner}/${job_config.pr_repo}/pull/${job_config.prNumber}"

                            echo "Searching for manifest PR..."
                            echo "Search text: ${searchText}"

                            int openPRCount  = 0
                            job_config.state = "open"
                            job_config.repo  = job_config.manifest_repo
                            def prs = utils.github.listPullRequests(job_config)

                            if (prs instanceof List) {
                                openPRCount = prs.size()
                                echo "Open PR count: ${openPRCount}"

                                for (def pr : prs) {
                                    if (pr.body?.contains(searchText)) {
                                        updateManifestPRnumber = pr.prNumber
                                        break
                                    }
                                }
                            }

                            echo "Checking through diff and try to find Manifest update PR"
                            def diff_pr = utils.github.findPRsWithDiff(a, "pull/${job_config.prNumber}/head")
                            if(updateManifestPRnumber == diff_pr.prNumber) {
                                echo "both way confirms manifest update found in PR#${updateManifestPRnumber}"
                            } else {
                                echo "found 2 manifest update PR PR#${updateManifestPRnumber} and ${diff_pr.prNumber}"
                                updateManifestPRnumber = diff_pr.prNumber
                            }

                            echo "Searching for manifest update message in comment..."
                            echo "Search comment: ${commentMsg}"
                            job_config.repo =  job_config.pr_repo
                            comment_id      = utils.github.getCommentID(job_config, commentMsg)
                    }
                }
            }
        }

        failure {
            echo "🚫 Build failed. Sending email..."
            script {
                emailext (
                    subject: "🚨 Jenkins Job Failed: ${env.JOB_NAME} [${env.BUILD_NUMBER}]",
                    body: """
                       <p>Build failed for job: <b>${env.CHANGE_URL}</b></p>
                       <p>Build Number: <b>${env.BUILD_NUMBER}</b></p>
                       <p>View details: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                    """,
                    to : "${allRecipientEmails}",
                    mimeType: 'text/html'
                )
                if (utils && utils.github) {
                    withCredentials([usernamePassword(credentialsId: job_config.github_creds_id,
                        usernameVariable: 'GITHUB_TOKEN_USR', passwordVariable: 'GITHUB_TOKEN')]) {
                            job_config.label = pr_labels[3]
                            echo "Add labels => ${job_config.label}"
                            utils.github.addLabel(job_config)
                    }
                }
            }
        }

        success {
            echo "🟢 UPDATING CORRESPONDING SHA/COMMIT-ID IN MANIFEST FILE OF ALIF_SDK 🟢"
            script {
                withCredentials([usernamePassword(credentialsId: '27c5d944-f190-4ab7-8c37-23cc43c7ce11',
                    usernameVariable: 'GITHUB_TOKEN_USR', passwordVariable: 'GITHUB_TOKEN')]) {

                        job_config.repo  = job_config.pr_repo
                        job_config.label = pr_labels[0]
                        echo "Add labels =>  ${job_config.label}"
                        utils.github.addLabel(job_config)

                        if (!updateManifestPRnumber && !comment_id) {
                            a.comment = commentMsg
                            utils.github.addComment(job_config)
                        }
                }
            }
        }

        cleanup {
            echo "Cleaning up workspace..."
            deleteDir()
        }
    }
}
